name: stelliberty
description: "星辰自由"

publish_to: 'none'

version: 1.1.20+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  # 桌面窗口控制
  bitsdojo_window: ^0.1.6
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  screen_retriever: ^0.2.0
  # Flutter ↔ Rust 通信
  # 生成桥接代码: rinf gen
  rinf: ^8.8.0
  # 本地存储
  shared_preferences: ^2.5.3
  # Tuple 支持
  tuple: ^2.0.2
  # Meta 注解支持
  meta: ^1.11.0
  # Google Fonts 支持
  google_fonts: ^6.3.1
  # 强调色支持
  system_theme: ^3.1.2
  # 窗口效果
  flutter_acrylic: ^1.1.4
  # 设备信息
  device_info_plus: ^12.1.0
  # 状态管理
  provider: ^6.1.5

  # 国际化支持
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_single_instance: ^1.6.0

  # HTTP 客户端
  http: ^1.2.2
  path: ^1.9.1
  path_provider: ^2.1.5
  
  # 文件压缩解压
  archive: ^4.0.7

  # YAML 解析
  yaml: ^3.1.3

  # 文件选择器
  file_picker: ^10.3.3
  # 拖放文件支持
  desktop_drop: ^0.7.0

  # 应用信息
  package_info_plus: ^9.0.0

  # 代码编辑器支持
  re_editor: ^0.8.0
  re_highlight: ^0.0.3

  # 可拖动排序的网格视图
  reorderable_grid_view: ^2.2.8

dev_dependencies:
  flutter_lints: ^6.0.0

  # 生成语言包: dart run slang
  slang_build_runner: ^4.8.0
  # 依赖检测：dart run dependency_validator
  dependency_validator: ^5.0.2
  # 包名重命名工具
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/clash-core/
    - assets/clash-core/data/
    - assets/service/

rinf:
  gen_input_crates:
    - hub
  gen_output_dir: lib/src/bindings